module: FileSelectorView
readme: README.md
clean: true
disable_search: true
author: Nef10
author_url: https://github.com/Nef10
root_url: https://Nef10.github.io/FileSelectorView/
github_url: https://github.com/Nef10/FileSelectorView
github_file_prefix: https://github.com/Nef10/FileSelectorView/blob/master
output: ./docs
theme: fullwidth
