name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Install Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: "5.2.0"
    - name: Build
      run: swift build
  swiftlint:
    name: SwiftLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Run SwiftLint --strict
        uses: norio-nomura/action-swiftlint@3.1.0
        with:
          args: --strict


          name: CI
